language: c
sudo: required
dist: trusty
services:
  - docker

# Don't build the pyup- branches that pyup.io creates; it's redundant
# with the PR builds that Travis also does.
branches:
  except:
    - /^pyup-/

env:
  global:
    - REPO: parsely/manylinux
    - secure: "CWp276rBejshFjMMECDnXkxFeFOa6vIYHlyoSqp+YKCGxxtZeTm/kgEu03FEpA29LYgAyV6onxaTtHc+4xBW1sVR5ZCYgET/H3tj+TkOQRDcB+dKbd+I133OidBIYnGfJ2M1ADwsx9QU8jcvFs2TiNFNU3sQ2A4BhhCMuUv6OKybG2RLvpDCT5XnyIhvXTLyTGFef/iRI8iufMZ1Xp9gGB/Tjk7soJJLcROa3r1ynb8ABNHRTFd9b0yEg9zjnZ9HGIODjO7Rii7cy8bAh/gKhmJRrMUCgutiVLibAXcsH+wpC5sQiUiFCnO/kRpK8rgRWbohLwwa5c1gV2Cqp43mZnkQksZ698lw67j3gigMJu2gf9/ceLkeC8EJsVsF61uNsqFQ8tBL0+lZV3JcLM1TN0tgoQBi/z5uMPv2sh3MeeXJlAo/YE7suqjmkRWXAisJmtPolufDMa7pBI99fYE5NWLmK4iV9HIIhNMgRMj5pEbXwt92LJPV6pPAoIUufVf1H3lC62BOhFDGF91RQ42Jm0Tm4WwZtW3AzXuB5YRpF4D2uFJXcRxvZy+QQHMHWAtX1L0Nn2p2QmvPYDcoJvzjHk3yYShG1xYeQfWtUPYLgU2avtp/MUT1f2qr6V1bmx8W0tfSOYKUzd3ehOBFvV/ua3R1AJzjKaE9d/5TY55ac9I="
    - secure: "Cs5g1y13xloO7y81CA5/ygLR09VikwR9MDFnbyOFNSlbaWBm0WNegKRhZjVCaS6pdlDJS9XMWfnF2FgQldy0JmWzafeyEFryIocEXT1VpHVzZQqgnrY3qLVRGnbWPdGYzKUI7eqxC/pbhTBOlh2xnTqEDu96t5omqsf70Pyt3MSLwRxKEm8joEX+jKV6O0ndNakkv6QtMnleKkEeMsBtZk8g+fMvOUkXhYhyr2HHPdp//lveNLmBPTRc9sN0fiUY6wMTvj8l3zf1gb76hSCqObcm8O5Rs92+ZX6Yy6BRc1+hhSYXwlD45M2ggDx3PPblr8+LgZN7iU3xrjYDB2CapeRnIAr1xBkewQlb777P+t9HbVWC12+gMORBH2gLHyvggDufQ4jnPo9rBrgB1erjDVdtD3VweQ/YDxOfmFXlzSz3jr85dQls4d7J+OxtofswKyCTciCLbIuU1sb+EzAdAymVz4C2pTyVuzFipO6T3GDbnHxReuIkx1Gz2VSl9FTyKsU0jHhVu512WfA+pu2pPEzUYKB80AEfT61xxRQF58NDFiKbmUl/+LsXPI9berf/KUzhi1gKoAciO8VJAJG75+Ho3ko/6CoLZr91d2AkxQqU4XMV4RovOV51JyVnodHvR7TW8XElhWAoEPN2dUDMBGxf+JszUDW6prqEzS6Hp9Y="
    - secure: "Nn2O7NZse6mq1vdgKUZZMYOWA6XZe0HRaYMpYdSyoIkXiOc7HTWwmem6yz3yASyG+9JYi3LBOXaxyajGw+wf6OM5ee7L8QIQrCorNA+ddm+xWVJbs0AQ5iFgMVjHH1m3bpWs5op5z+ehnZbSYGet10sBM8DRG38QCIJOSZSnVIfy4VMmDmX9KnCYJlYLpCNjJjbmw+UMq5HOZ1Ogp6M3qraf3jsuxWcZ171g/M6OUhpmh3DxzqZhcwa3PlNWkMaJTIErW6wBnaUKFV+7ke9+2/Oyos4upGE2imTiDXcTQsS22X/mIXBL+/JVb/OFldEvYS466fyAHAJwxUNrA1ov8LHxr/9nshTq3NaBbwHfySkMQA6RHc6WAGiyD0dTMV/WE04PzgG1XIeGaXelakAxzgN8QXHPEyqJY3zNdiGqmqWWfuruoGWC+7JRqhVrWCAtv2NwevRu6cIh9dV6ezYYPuIcvq11uPxpdUiuhEIWaHBFy93I6o/G3jZGOy1nszVLznQYQ+JoIXMi/CeauG3kWz9TEFUyAIh8Zj6nFeXagI5mBcNQTqNSg/uw4+taKymZNVdno4i3S2A8/6qh6uXVGtb7WD1zlULAbAU174fD2IwPv9G/MpSUov/D97/3euK3BIoCl7OOC4XOnNGgF4TfX++XUGyTcbKbigOj3QCYO3U="

script:
  - REPO=$REPO TRAVIS_COMMIT=$TRAVIS_COMMIT ./build.sh

deploy:
  provider: script
  script: docker/deploy.sh
  on:
    branch: master
    repo: pypa/manylinux
