language: c
os: linux
dist: focal
services:
  - docker

# Don't build the update-dependencies-pr branch; it's redundant
# with the PR builds that Travis also does.
branches:
  except:
    - /^update-dependencies-pr/

jobs:
   include:
    - arch: ppc64le

script: |
  for version in 3.12 3.13 3.14 3.15 3.16; do
    docker pull -q ppc64le/alpine:$version 2>&1 1>/dev/null
    echo "Alpine ${version}:"
    docker run --rm -t ppc64le/alpine:$version sh -c "apk add -q python3 2>&1 1>/dev/null; python3 -c 'import struct; print(struct.Struct(\"!f\").pack(1.0).hex())'"
  done
  docker pull -q quay.io/pypa/musllinux_1_1_ppc64le:latest 2>&1 1>/dev/null
  for version in 3.6 3.7 3.8 3.9 3.10 3.11; do
    echo "musllinux python ${version}:"
    docker run -t --rm quay.io/pypa/musllinux_1_1_ppc64le:latest python${version} -c 'import struct; print(struct.Struct("!f").pack(1.0).hex())'
  done
